## Subvert defaults - USER: do NOT edit this file, edit the config.py copy created on first use
#
# Default settings all go here
default_settings = {
    "stash_url": "http://localhost:9999",
    "stash_tmpdir": "/root/stash_tmp/",
    "stash_logfile": "",
    "batch_quantity": 10,
    "subtitle_tag_id": 0,
}
